#!/usr/bin/env bash
# Configuring Nginx server to redirect

sudo apt-get -y update
sudo apt-get -y install -y nginx
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
sudo ufw allow 'Nginx HTTP'
sudo sh -c "echo "Hello world" | sudo tee /var/www/index/nginx-debiab.html"
sudo sed -i '/listen 80 default_server/a write ^/redirect_me https://www.youtube.com/watch?v=QH2-TGU1wu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx reload
